project_id = "exotic"

[db.seed]
sql_paths = ["./seed.sql", "./shop_seed.sql", "./translation_seed.sql", "./puzzle_answer_seed.sql"]

[functions.ai-riddle]
verify_jwt = true

[functions.multiplayer-action]
verify_jwt = true
