-- Generated localized word-answer entries for server-side validation.
insert into public.translation_entries(catalog_id, key, value)
select catalog.id, seed.key, seed.value
from (values
  ('en', 'puzzle.answer.key', 'key'),
  ('en', 'puzzle.answer.pencil', 'pencil'),
  ('en', 'puzzle.answer.cheetah', 'cheetah'),
  ('en', 'puzzle.answer.watch', 'watch'),
  ('en', 'puzzle.answer.clock', 'clock'),
  ('en', 'puzzle.answer.keyring', 'keyring'),
  ('en', 'puzzle.answer.book', 'book'),
  ('ar', 'puzzle.answer.key', 'مفتاح'),
  ('ar', 'puzzle.answer.pencil', 'قلم رصاص'),
  ('ar', 'puzzle.answer.cheetah', 'فهد'),
  ('ar', 'puzzle.answer.watch', 'ساعة'),
  ('ar', 'puzzle.answer.clock', 'ساعة'),
  ('ar', 'puzzle.answer.keyring', 'حلقة مفاتيح'),
  ('ar', 'puzzle.answer.book', 'كتاب'),
  ('fr', 'puzzle.answer.key', 'clé'),
  ('fr', 'puzzle.answer.pencil', 'crayon'),
  ('fr', 'puzzle.answer.cheetah', 'guépard'),
  ('fr', 'puzzle.answer.watch', 'montre'),
  ('fr', 'puzzle.answer.clock', 'horloge'),
  ('fr', 'puzzle.answer.keyring', 'porte-clés'),
  ('fr', 'puzzle.answer.book', 'livre'),
  ('es', 'puzzle.answer.key', 'llave'),
  ('es', 'puzzle.answer.pencil', 'lápiz'),
  ('es', 'puzzle.answer.cheetah', 'guepardo'),
  ('es', 'puzzle.answer.watch', 'reloj'),
  ('es', 'puzzle.answer.clock', 'reloj'),
  ('es', 'puzzle.answer.keyring', 'llavero'),
  ('es', 'puzzle.answer.book', 'libro'),
  ('de', 'puzzle.answer.key', 'Schlüssel'),
  ('de', 'puzzle.answer.pencil', 'Bleistift'),
  ('de', 'puzzle.answer.cheetah', 'Gepard'),
  ('de', 'puzzle.answer.watch', 'Uhr'),
  ('de', 'puzzle.answer.clock', 'Uhr'),
  ('de', 'puzzle.answer.keyring', 'Schlüsselring'),
  ('de', 'puzzle.answer.book', 'Buch'),
  ('pt', 'puzzle.answer.key', 'chave'),
  ('pt', 'puzzle.answer.pencil', 'lápis'),
  ('pt', 'puzzle.answer.cheetah', 'guazepardo'),
  ('pt', 'puzzle.answer.watch', 'relógio'),
  ('pt', 'puzzle.answer.clock', 'relógio'),
  ('pt', 'puzzle.answer.keyring', 'chaveiro'),
  ('pt', 'puzzle.answer.book', 'livro'),
  ('it', 'puzzle.answer.key', 'chiave'),
  ('it', 'puzzle.answer.pencil', 'matita'),
  ('it', 'puzzle.answer.cheetah', 'ghepardo'),
  ('it', 'puzzle.answer.watch', 'orologio'),
  ('it', 'puzzle.answer.clock', 'orologio'),
  ('it', 'puzzle.answer.keyring', 'portachiavi'),
  ('it', 'puzzle.answer.book', 'libro'),
  ('nl', 'puzzle.answer.key', 'sleutel'),
  ('nl', 'puzzle.answer.pencil', 'potlood'),
  ('nl', 'puzzle.answer.cheetah', 'jachtluipaard'),
  ('nl', 'puzzle.answer.watch', 'horloge'),
  ('nl', 'puzzle.answer.clock', 'klok'),
  ('nl', 'puzzle.answer.keyring', 'sleutelring'),
  ('nl', 'puzzle.answer.book', 'boek'),
  ('ru', 'puzzle.answer.key', 'ключ'),
  ('ru', 'puzzle.answer.pencil', 'карандаш'),
  ('ru', 'puzzle.answer.cheetah', 'гепард'),
  ('ru', 'puzzle.answer.watch', 'часы'),
  ('ru', 'puzzle.answer.clock', 'часы'),
  ('ru', 'puzzle.answer.keyring', 'связка ключей'),
  ('ru', 'puzzle.answer.book', 'книга'),
  ('tr', 'puzzle.answer.key', 'anahtar'),
  ('tr', 'puzzle.answer.pencil', 'kalem'),
  ('tr', 'puzzle.answer.cheetah', 'çita'),
  ('tr', 'puzzle.answer.watch', 'saat'),
  ('tr', 'puzzle.answer.clock', 'saat'),
  ('tr', 'puzzle.answer.keyring', 'anahtarlık'),
  ('tr', 'puzzle.answer.book', 'kitap'),
  ('ja', 'puzzle.answer.key', 'かぎ'),
  ('ja', 'puzzle.answer.pencil', 'えんぴつ'),
  ('ja', 'puzzle.answer.cheetah', 'チータ'),
  ('ja', 'puzzle.answer.watch', 'かいちゅうどけい'),
  ('ja', 'puzzle.answer.clock', 'とけい'),
  ('ja', 'puzzle.answer.keyring', 'かぎたば'),
  ('ja', 'puzzle.answer.book', 'ほん'),
  ('ko', 'puzzle.answer.key', '열쇠'),
  ('ko', 'puzzle.answer.pencil', '연필'),
  ('ko', 'puzzle.answer.cheetah', '치타'),
  ('ko', 'puzzle.answer.watch', '손목시계'),
  ('ko', 'puzzle.answer.clock', '시계'),
  ('ko', 'puzzle.answer.keyring', '열쇠고리'),
  ('ko', 'puzzle.answer.book', '책'),
  ('zh', 'puzzle.answer.key', '钥匙'),
  ('zh', 'puzzle.answer.pencil', '铅笔'),
  ('zh', 'puzzle.answer.cheetah', '猎豹'),
  ('zh', 'puzzle.answer.watch', '手表'),
  ('zh', 'puzzle.answer.clock', '时钟'),
  ('zh', 'puzzle.answer.keyring', '钥匙环'),
  ('zh', 'puzzle.answer.book', '书'),
  ('hi', 'puzzle.answer.key', 'चाबी'),
  ('hi', 'puzzle.answer.pencil', 'पेंसिल'),
  ('hi', 'puzzle.answer.cheetah', 'चीता'),
  ('hi', 'puzzle.answer.watch', 'हाथ की घड़ी'),
  ('hi', 'puzzle.answer.clock', 'घड़ी'),
  ('hi', 'puzzle.answer.keyring', 'चाबियों का गुच्छा'),
  ('hi', 'puzzle.answer.book', 'किताब'),
  ('id', 'puzzle.answer.key', 'kunci'),
  ('id', 'puzzle.answer.pencil', 'pensil'),
  ('id', 'puzzle.answer.cheetah', 'cheetah'),
  ('id', 'puzzle.answer.watch', 'jam tangan'),
  ('id', 'puzzle.answer.clock', 'jam dinding'),
  ('id', 'puzzle.answer.keyring', 'gantungan kunci'),
  ('id', 'puzzle.answer.book', 'buku'),
  ('ur', 'puzzle.answer.key', 'چابی'),
  ('ur', 'puzzle.answer.pencil', 'پینسل'),
  ('ur', 'puzzle.answer.cheetah', 'چیتا'),
  ('ur', 'puzzle.answer.watch', 'دستی گھڑی'),
  ('ur', 'puzzle.answer.clock', 'گھڑی'),
  ('ur', 'puzzle.answer.keyring', 'چابیوں کا انگوٹھا'),
  ('ur', 'puzzle.answer.book', 'کتاب')
) as seed(locale, key, value)
join public.translation_catalogs catalog on catalog.locale = seed.locale
on conflict (catalog_id, key) do update set value = excluded.value;
